import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { watch } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";

const root = process.cwd();
const sourceRoot = resolve(root, "src");
const generatedVendorAssetPath = resolve(root, "src/generated/vendorAssets.js");
const watchMode = process.argv.includes("--watch");
const externalModules = ["child_process", "obsidian"];
const requiredFiles = [
  "manifest.json",
  "styles.css",
  "src/main.js",
  "src/vendor/unpdf/pdfjs.mjs.base64"
];

function toModuleId(filePath) {
  return relative(root, filePath).replaceAll("\\", "/");
}

function readTextFileNormalized(filePath) {
  return readFileSync(filePath, "utf8").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

function collectJavaScriptFiles(directory) {
  const entries = readdirSync(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectJavaScriptFiles(entryPath));
      continue;
    }

    if (extname(entry.name) === ".js") {
      files.push(entryPath);
    }
  }

  return files.sort();
}

function writeGeneratedVendorAssetModule() {
  mkdirSync(dirname(generatedVendorAssetPath), { recursive: true });
  const pdfJsBase64 = readFileSync(resolve(root, "src/vendor/unpdf/pdfjs.mjs.base64"), "utf8").replace(/\s+/g, "");
  const source = [
    "const UNPDF_PDFJS_MODULE_BASE64 = ",
    JSON.stringify(pdfJsBase64),
    ";\n\nmodule.exports = {\n  UNPDF_PDFJS_MODULE_BASE64\n};\n"
  ].join("");

  if (existsSync(generatedVendorAssetPath) && readFileSync(generatedVendorAssetPath, "utf8") === source) {
    return;
  }

  writeFileSync(generatedVendorAssetPath, source, "utf8");
}

function createBundle() {
  writeGeneratedVendorAssetModule();

  const modules = collectJavaScriptFiles(sourceRoot).map((filePath) => {
    const id = toModuleId(filePath);
    const source = readTextFileNormalized(filePath);
    return [
      `  ${JSON.stringify(id)}: function(module, exports, require) {`,
      source
        .split("\n")
        .map((line) => line === "" ? "" : `    ${line}`)
        .join("\n"),
      "  }"
    ].join("\n");
  });

  return [
    "/* CoDriver Obsidian plugin entrypoint. Generated by scripts/build.mjs. */",
    "(function() {",
    "  const __modules = {",
    modules.join(",\n"),
    "  };",
    "  const __cache = {};",
    "",
    "  function __resolve(request, parentId) {",
    "    if (!request.startsWith('.')) {",
    "      return request;",
    "    }",
    "",
    "    const parts = parentId.split('/');",
    "    parts.pop();",
    "",
    "    for (const segment of request.split('/')) {",
    "      if (segment === '.' || segment === '') {",
    "        continue;",
    "      }",
    "",
    "      if (segment === '..') {",
    "        parts.pop();",
    "        continue;",
    "      }",
    "",
    "      parts.push(segment);",
    "    }",
    "",
    "    let resolved = parts.join('/');",
    "    if (!resolved.endsWith('.js')) {",
    "      resolved = `${resolved}.js`;",
    "    }",
    "",
    "    return resolved;",
    "  }",
    "",
    "  function __load(request, parentId) {",
    "    const id = parentId ? __resolve(request, parentId) : request;",
    `    const externalModules = new Set(${JSON.stringify(externalModules)});`,
    "    if (externalModules.has(id)) {",
    "      return require(id);",
    "    }",
    "",
    "    const moduleFactory = __modules[id];",
    "    if (!moduleFactory) {",
    "      throw new Error(`Cannot find bundled module '${id}' required from '${parentId || '<entry>'}'.`);",
    "    }",
    "",
    "    if (__cache[id]) {",
    "      return __cache[id].exports;",
    "    }",
    "",
    "    const module = { exports: {} };",
    "    __cache[id] = module;",
    "    moduleFactory(module, module.exports, (nextRequest) => __load(nextRequest, id));",
    "    return module.exports;",
    "  }",
    "",
    "  module.exports = __load('src/main.js');",
    "}());",
    ""
  ].join("\n");
}

function build() {
  const missing = requiredFiles.filter((file) => !existsSync(resolve(root, file)));
  if (missing.length > 0) {
    throw new Error(`Missing required file(s): ${missing.join(", ")}`);
  }

  writeFileSync(resolve(root, "main.js"), createBundle(), "utf8");

  console.log("Built main.js");
}

build();

if (watchMode) {
  console.log("Watching src for changes...");
  const rebuild = () => {
    try {
      build();
    } catch (error) {
      console.error(error instanceof Error ? error.message : String(error));
    }
  };

  watch(resolve(root, "src"), { recursive: true }, rebuild);
}
