const VIEW_TYPE_CODRIVER = "codriver-chat-view";
const CODRIVER_PLUGIN_VERSION = "0.5.1";
const DEFAULT_OPENAI_COMPATIBLE_BASE_URL = "http://localhost:1234/v1";
const DEFAULT_GEMINI_BASE_ENDPOINT = "https://generativelanguage.googleapis.com";
const DEFAULT_GEMINI_API_VERSION = "v1beta";
const DEFAULT_ANTHROPIC_BASE_ENDPOINT = "https://api.anthropic.com";
const DEFAULT_ANTHROPIC_API_VERSION = "2023-06-01";
const DEFAULT_ANTHROPIC_MAX_OUTPUT_TOKENS = 8192;
const OPENAI_PROVIDER_TYPE = "openAI";
const OPENAI_COMPATIBLE_PROVIDER_TYPE = OPENAI_PROVIDER_TYPE;
const GEMINI_PROVIDER_TYPE = "Gemini";
const ANTHROPIC_PROVIDER_TYPE = "Anthropic";
const DEFAULT_OPENAI_COMPATIBLE_PROVIDER_ID = "openai-compatible-local";
const DEFAULT_OPENAI_COMPATIBLE_PROVIDER_NAME = "OpenAI-compatible";
const DEFAULT_GEMINI_PROVIDER_ID = "gemini";
const DEFAULT_GEMINI_PROVIDER_NAME = "Gemini";
const DEFAULT_ANTHROPIC_PROVIDER_ID = "anthropic";
const DEFAULT_ANTHROPIC_PROVIDER_NAME = "Anthropic";
const MCP_PROTOCOL_VERSION = "2025-06-18";
const MCP_STDIO_TRANSPORT = "stdio";
const MCP_HTTP_TRANSPORT = "http";

module.exports = {
  VIEW_TYPE_CODRIVER,
  CODRIVER_PLUGIN_VERSION,
  DEFAULT_OPENAI_COMPATIBLE_BASE_URL,
  DEFAULT_GEMINI_BASE_ENDPOINT,
  DEFAULT_GEMINI_API_VERSION,
  DEFAULT_ANTHROPIC_BASE_ENDPOINT,
  DEFAULT_ANTHROPIC_API_VERSION,
  DEFAULT_ANTHROPIC_MAX_OUTPUT_TOKENS,
  OPENAI_PROVIDER_TYPE,
  OPENAI_COMPATIBLE_PROVIDER_TYPE,
  GEMINI_PROVIDER_TYPE,
  ANTHROPIC_PROVIDER_TYPE,
  DEFAULT_OPENAI_COMPATIBLE_PROVIDER_ID,
  DEFAULT_OPENAI_COMPATIBLE_PROVIDER_NAME,
  DEFAULT_GEMINI_PROVIDER_ID,
  DEFAULT_GEMINI_PROVIDER_NAME,
  DEFAULT_ANTHROPIC_PROVIDER_ID,
  DEFAULT_ANTHROPIC_PROVIDER_NAME,
  MCP_HTTP_TRANSPORT,
  MCP_PROTOCOL_VERSION,
  MCP_STDIO_TRANSPORT
};
